vagrantfile-local:
    vm:
        box: centos6
        box_url: http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-puppet.box
        hostname: devopstest
        domain: drupal.org
        memory: '2048'
        network:
          private_network: 192.168.56.101
          forwarded_port:
              http:
                  host: '8081'
                  guest: '80'
              https:
                  host: '4297'
                  guest: '443'
